position(nader_al_sayed,goalie).
position(amir_abdul_hamid,goalie).
position(essam_al_hadari,goalie).
position(ahmed_sayed,defender).
position(emad_nahhas,defender).
position(shadi_mohamed,defender).
position(rami_adel,defender).
position(wael_gomaa,defender).
position(mohamed_abdul_wahab,defender).
position(islam_al_shater,defender).
position(amr_al_halawni,defender).
position(abdel_ellah_galal,defender).
position(akwetey_mensah,center).
position(hady_khashaba,center).
position(hassan_mostafa,center).
position(wael_reyad,center).
position(amaral_sebastiao_dag,center).
position(mohamed_abou_treika,center).
position(ahmed_hassan,center).
position(mohamed_barakat,center).
position(mohamed_shawki,center).
position(hossam_ashour,center).
position(ahmed_shedid,center).
position(mohamed_abdallah,center).
position(amr_fathi,center).
position(ahmed_samir_farag,center).
position(haytham_al_fazani,center).
position(osama_hosni,leftwinger).
position(emad_meteb,leftwinger).
position(flavio_amado,rightwinger).
position(sherif_ashraf,rightwinger).

position(abdul_wahed_al_sayed,goalie).
position(mohammed_abdul_monsef,goalie).
position(wael_ismael,goalie).
position(tarek_al_sayed,defender).
position(wael_al_qabani,defender).
position(mohamed_sedik,defender).
position(medhat_abdul_hadi,defender).
position(mahmoud_mahmoud,defender).
position(ahmed_bakri,defender).
position(farag_shalabi,defender).
position(ahmed_hossam,defender).
position(tamer_abdul_wahab,defender).
position(youssef_hamdi,center).
position(adel_fathi,center).
position(mohamed_aboul_ella,center).
position(hazem_emam,center).
position(tarek_saied,center).
position(tamer_abdul_hamid,center).
position(mohamed_abdul_wahed,center).
position(sameh_youssef,center).
position(moetazbellah_mohamed,center).
position(ibrahim_saied,center).
position(awuley_quaye_jr,center).
position(alaa_abdul_ghani,center).
position(mostafa_gaafar,leftwinger).
position(gamal_hamza,leftwinger).
position(waleed_abdul_latif,leftwinger).
position(abdul_halim_ali,rightwinger).
position(hossam_osama,rightwinger).
position(edson_rolando_silva_souza,rightwinger).
position(kingsley_sunny_ekeh,rightwinger).

position(wessam_ismael,goalie).
position(essam_mahmoud,goalie).
position(mostafa_kamal,goalie).
position(mahmoud_bayoumi,defender).
position(ahmed_abdul_hakam,defender).
position(mohammed_al_zayat,defender).
position(amr_abdelaziz,defender).
position(mohammed_gaber,defender).
position(omar_khatab,defender).
position(osama_hassan,defender).
position(moataz_hamed,defender).
position(mohammed_al_hadidy,defender).
position(mohammed_youness,defender).
position(amr_fahim,defender).
position(ayman_said,center).
position(ahmed_salah,center).
position(reda_shehata,center).
position(mostafa_al_sharkawy,center).
position(samir_sabri,leftwinger).
position(hany_abdallah,righttwinger).
position(fouad_salama,center).
position(mohammed_sabet,leftwinger).
position(magdy_atwa,center).
position(abdel_aziz_tawfik,center).
position(ghazali_mohammed,center).
position(ashour_al_taqui,center).
position(mohammed_ibrahim,center).
position(ahmed_abdul_zaher,leftwinger).
position(amr_zaki,leftwinger).
position(magdy_abdelaaty,leftwinger).
position(hossam_mabrouk,rightwinger).
position(abdelhamid_hassan,leftwinger).

position(haytham_hassan,goalie).
position(ndubuisi_egbo,french).
position(ndubuisi_egbo,italian).
position(fawzy_samir,goalie).
position(mohammed_mostafa_helwa,defender).
position(amr_al_safty,defender).
position(ibrahim_hassan,defender).
position(osama_ragab,defender).
position(mohammed_emara,defender).
position(samir_kamouna,defender).
position(karim_zekry,defender).
position(haytham_farouk,defender).
position(mohammed_salah,defender).
position(hani_saiid,defender).
position(mahmoud_eid,defender).
position(osama_al_sayed,defender).
position(abdallah_ragab,center).
position(ahmed_hafez,center).
position(mohammed_al_rayes,center).
position(salah_amin,center).
position(ahmed_farghali,center).
position(mahmoud_saad,center).
position(ashour_al_adham,center).
position(amr_bassiouny,center).
position(al_sayed_al_atbani,rightwinger).
position(hossam_hassan,leftwinger).
position(saliu_cobblah,leftwinger).
position(mohammed_zekri,leftwinger).
position(mohammed_fadl,rightwinger).
position(mohammed_al_genedy,leftwinger).
position(geoffrey_massa,rightwinger).

position(shady_al_maamour,goalie).
position(mohammed_al_akabawy,goalie).
position(daouda_diakite,goalie).
position(youssef_abdelrahman,defender).
position(mohammed_abdelsatar,defender).
position(rami_hanafi,defender).
position(mohammed_gamal,defender).
position(mohammed_al_etrawy,defender).
position(mohammed_ali,defender).
position(ibrahim_al_bahnasi,defender).
position(mohammed_al_ghanam,defender).
position(khaled_nabil,defender).
position(mohammed_ouda,defender).
position(mohamed_al_hosari,defender).
position(sherif_al_beyali,center).
position(mohammed_muselhy,center).
position(ahmed_mahmoud,center).
position(ayman_zein,center).
position(mahmoud_samir,center).
position(ehab_al_masri,center).
position(amir_salah,rightwinger).
position(mohammed_fahim,leftwinger).
position(tamer_adel,rightwinger).
position(talaat_moharam,leftwinger).

position(mohammed_fathi,goalie).
position(mohammed_sobhi,goalie).
position(amr_al_desouki,defender).
position(mahmoud_selim,defender).
position(moatasem_salem,defender).
position(sayed_moawad,defender).
position(ahmed_al_gamal,defender).
position(hesham_ali,defender).
position(sherif_abd_al_fadil,defender).
position(ahmed_saied,defender).
position(ayman_ramadan,defender).
position(ibrahim_yehia,defender).
position(ahmed_abdul_aziz,defender).
position(ahmed_khairy,defender).
position(samuel_johnson,center).
position(ahmed_fathi,center).
position(ali_gomaa,center).
position(omar_gamal,center).
position(abdallah_al_shahat,center).
position(mohammed_soliman,center).
position(ahmed_khalifa,center).
position(mohammed_gouda,center).
position(abdallah_al_saiid,center).
position(mohammed_mohsen,leftwinger).
position(youssef_gamal,rightwinger).
position(robert_akaruye,leftwinger).
position(mohammed_salah_abou_greisha,rightwinger).
position(jorge_celino,leftwinger).
position(islam_shokri,rightwinger).
position(mohammed_abdrabu,leftwinger).

language(mohammed_fathi,arabic).
language(mohammed_fathi,arabic).
language(mohammed_sobhi,italian).
language(amr_al_desouki,arabic).
language(mahmoud_selim,arabic).
language(moatasem_salem,french).
language(sayed_moawad,arabic).
language(sayed_moawad,french).
language(ahmed_al_gamal,arabic).
language(hesham_ali,arabic).
language(hesham_ali,english).
language(sherif_abd_al_fadil,arabic).
language(ahmed_saied,arabic).
language(ayman_ramadan,arabic).
language(ibrahim_yehia,arabic).
language(ahmed_abdul_aziz,arabic).
language(ahmed_khairy,arabic).
language(samuel_johnson,french).
language(ahmed_fathi,arabic).
language(ali_gomaa,arabic).
language(omar_gamal,arabic).
language(abdallah_al_shahat,arabic).
language(mohammed_soliman,arabic).
language(hesham_ali,arabic).
language(hesham_ali,english).
language(hesham_ali,italian).
language(mohammed_mohsen,arabic).
language(youssef_gamal,arabic).
language(robert_akaruye,english).
language(mohammed_salah_abou_greisha,arabic).
language(jorge_celino,italian).
language(jorge_celino,french).
language(jorge_celino,english).
language(islam_shokri,arabic).
language(mohammed_abdrabu,arabic).
language(mohammed_abdrabu,english).

language(wessam_ismael,arabic).
language(essam_mahmoud,arabic).
language(mostafa_kamal,arabic).
language(mostafa_kamal,english).
language(mahmoud_bayoumi,arabic).
language(ahmed_abdul_hakam,arabic).
language(mohammed_al_zayat,arabic).
language(amr_abdelaziz,arabic).
language(mohammed_gaber,arabic).
language(omar_khatab,arabic).
language(osama_hassan,arabic).
language(moataz_hamed,arabic).
language(mohammed_al_hadidy,arabic).
language(mohammed_youness,arabic).
language(amr_fahim,arabic).
language(ayman_said,arabic).
language(ayman_said,english).
language(ahmed_salah,arabic).
language(reda_shehata,arabic).
language(mostafa_al_sharkawy,arabic).
language(samir_sabri,arabic).
language(hany_abdallah,arabic).
language(fouad_salama,arabic).
language(mohammed_sabet,arabic).
language(magdy_atwa,arabic).
language(abdel_aziz_tawfik,arabic).
language(ghazali_mohammed,french).
language(ghazali_mohammed,english).
language(ashour_al_taqui,arabic).
language(mohammed_ibrahim,arabic).
language(ahmed_abdul_zaher,arabic).
language(amr_zaki,arabic).
language(amr_zaki,italian).
language(magdy_abdelaaty,arabic).
language(hossam_mabrouk,arabic).
language(abdelhamid_hassan,arabic).
language(abdelhamid_hassan,french).

language(abdul_wahed_al_sayed,arabic).
language(mohammed_abdul_monsef,arabic).
language(wael_ismael,arabic).
language(tarek_al_sayed,arabic).
language(wael_al_qabani,arabic).
language(mohamed_sedik,arabic).
language(medhat_abdul_hadi,arabic).
language(mahmoud_mahmoud,arabic).
language(ahmed_bakri,arabic).
language(farag_shalabi,arabic).
language(ahmed_hossam,arabic).
language(tamer_abdul_wahab,arabic).
language(youssef_hamdi,arabic).
language(adel_fathi,arabic).
language(mohamed_aboul_ella,arabic).
language(hazem_emam,arabic).
language(tarek_saied,arabic).
language(tamer_abdul_hamid,arabic).
language(mohamed_abdul_wahed,arabic).
language(sameh_youssef,arabic).
language(moetazbellah_mohamed,arabic).
language(ibrahim_saied,arabic).
language(awuley_quaye_jr,french).
language(alaa_abdul_ghani,arabic).
language(mostafa_gaafar,arabic).
language(gamal_hamza,arabic).
language(waleed_abdul_latif,arabic).
language(abdul_halim_ali,arabic).
language(hossam_osama,arabic).
language(edson_rolando_silva_souza,ilatian).
language(kingsley_sunny_ekeh,ilatian).

language(nader_al_sayed,arabic).
language(amir_abdul_hamid,arabic).
language(essam_al_hadari,arabic).
language(ahmed_sayed,arabic).
language(ahmed_sayed,english).
language(emad_nahhas,arabic).
language(shadi_mohamed,arabic).
language(rami_adel,arabic).
language(wael_gomaa,arabic).
language(mohamed_abdul_wahab,arabic).
language(islam_al_shater,arabic).
language(amr_al_halawni,arabic).
language(abdel_ellah_galal,arabic).
language(akwetey_mensah,english).
language(hady_khashaba,arabic).
language(hady_khashaba,french).
language(hassan_mostafa,arabic).
language(wael_reyad,arabic).
language(amaral_sebastiao_dag,french).
language(mohamed_abou_treika,arabic).
language(ahmed_hassan,arabic).
language(mohamed_barakat,arabic).
language(mohamed_barakat,english).
language(mohamed_shawki,arabic).
language(hossam_ashour,arabic).
language(ahmed_shedid,arabic).
language(mohamed_abdallah,arabic).
language(amr_fathi,arabic).
language(ahmed_samir_farag,arabic).
language(haytham_al_fazani,arabic).
language(osama_hosni,arabic).
language(osama_hosni,english).
language(emad_meteb,arabic).
language(flavio_amado,french).
language(flavio_amado,english).
language(sherif_ashraf,arabic).

language(haytham_hassan,arabic).
language(ndubuisi_egbo,english).
language(ndubuisi_egbo,italian).
language(fawzy_samir,arabic).
language(mohammed_mostafa_helwa,arabic).
language(amr_al_safty,arabic).
language(ibrahim_hassan,arabic).
language(osama_ragab,arabic).
language(mohammed_emara,arabic).
language(samir_kamouna,arabic).
language(karim_zekry,arabic).
language(haytham_farouk,arabic).
language(mohammed_salah,arabic).
language(hani_saiid,arabic).
language(mahmoud_eid,arabic).
language(osama_al_sayed,arabic).
language(abdallah_ragab,arabic).
language(ahmed_hafez,arabic).
language(mohammed_al_rayes,arabic).
language(salah_amin,arabic).
language(ahmed_farghali,arabic).
language(mahmoud_saad,arabic).
language(ashour_al_adham,arabic).
language(amr_bassiouny,arabic).
language(al_sayed_al_atbani,arabic).
language(hossam_hassan,arabic).
language(saliu_cobblah,english).
language(saliu_cobblah,french).
language(mohammed_zekri,arabic).
language(mohammed_fadl,arabic).
language(mohammed_al_genedy,arabic).
language(geoffrey_massa,english).
language(geoffrey_massa,italian).

language(shady_al_maamour,arabic).
language(mohammed_al_akabawy,arabic).
language(daouda_diakite,french).
language(daouda_diakite,english).
language(daouda_diakite,italian).
language(youssef_abdelrahman,arabic).
language(mohammed_abdelsatar,arabic).
language(rami_hanafi,arabic).
language(mohammed_gamal,arabic).
language(mohammed_al_etrawy,arabic).
language(mohammed_ali,arabic).
language(ibrahim_al_bahnasi,arabic).
language(mohammed_al_ghanam,arabic).
language(khaled_nabil,arabic).
language(khaled_nabil,english).
language(mohammed_ouda,arabic).
language(mohamed_al_hosari,arabic).
language(sherif_al_beyali,french).
language(sherif_al_beyali,arabic).
language(mohammed_muselhy,arabic).
language(ahmed_mahmoud,arabic).
language(ayman_zein,arabic).
language(mahmoud_samir,arabic).
language(ehab_al_masri,arabic).
language(ehab_al_masri,french).
language(amir_salah,arabic).
language(mohammed_fahim,arabic).
language(mohammed_fahim,english).
language(tamer_adel,arabic).
language(talaat_moharam,arabic).


club(nader_al_sayed,ahly).
club(amir_abdul_hamid,ahly).
club(essam_al_hadari,ahly).
club(ahmed_sayed,ahly).
club(emad_nahhas,ahly).
club(shadi_mohamed,ahly).
club(rami_adel,ahly).
club(wael_gomaa,ahly).
club(mohamed_abdul_wahab,ahly).
club(islam_al_shater,ahly).
club(amr_al_halawni,ahly).
club(abdel_ellah_galal,ahly).
club(akwetey_mensah,ahly).
club(hady_khashaba,ahly).
club(hassan_mostafa,ahly).
club(wael_reyad,ahly).
club(amaral_sebastiao_dag,ahly).
club(mohamed_abou_treika,ahly).
club(ahmed_hassan,ahly).
club(mohamed_barakat,ahly).
club(mohamed_shawki,ahly).
club(hossam_ashour,ahly).
club(ahmed_shedid,ahly).
club(mohamed_abdallah,ahly).
club(amr_fathi,ahly).
club(ahmed_samir_farag,ahly).
club(haytham_al_fazani,ahly).
club(osama_hosni,ahly).
club(emad_meteb,ahly).
club(flavio_amado,ahly).
club(sherif_ashraf,ahly).

club(abdul_wahed_al_sayed,zamalek).
club(mohammed_abdul_monsef,zamalek).
club(wael_ismael,zamalek).
club(tarek_al_sayed,zamalek).
club(wael_al_qabani,zamalek).
club(mohamed_sedik,zamalek).
club(medhat_abdul_hadi,zamalek).
club(mahmoud_mahmoud,zamalek).
club(ahmed_bakri,zamalek).
club(farag_shalabi,zamalek).
club(ahmed_hossam,zamalek).
club(tamer_abdul_wahab,zamalek).
club(youssef_hamdi,zamalek).
club(adel_fathi,zamalek).
club(mohamed_aboul_ella,zamalek).
club(hazem_emam,zamalek).
club(tarek_saied,zamalek).
club(tamer_abdul_hamid,zamalek).
club(mohamed_abdul_wahed,zamalek).
club(sameh_youssef,zamalek).
club(moetazbellah_mohamed,zamalek).
club(ibrahim_saied,zamalek).
club(awuley_quaye_jr,zamalek).
club(alaa_abdul_ghani,zamalek).
club(mostafa_gaafar,zamalek).
club(gamal_hamza,zamalek).
club(waleed_abdul_latif,zamalek).
club(abdul_halim_ali,zamalek).
club(hossam_osama,zamalek).
club(edson_rolando_silva_souza,zamalek).
club(kingsley_sunny_ekeh,zamalek).

club(wessam_ismael,enppi).
club(essam_mahmoud,enppi).
club(mostafa_kamal,enppi).
club(mahmoud_bayoumi,enppi).
club(ahmed_abdul_hakam,enppi).
club(mohammed_al_zayat,enppi).
club(amr_abdelaziz,enppi).
club(mohammed_gaber,enppi).
club(omar_khatab,enppi).
club(osama_hassan,enppi).
club(moataz_hamed,enppi).
club(mohammed_al_hadidy,enppi).
club(mohammed_youness,enppi).
club(amr_fahim,enppi).
club(ayman_said,enppi).
club(ahmed_salah,enppi).
club(reda_shehata,enppi).
club(mostafa_al_sharkawy,enppi).
club(samir_sabri,enppi).
club(hany_abdallah,enppi).
club(fouad_salama,enppi).
club(mohammed_sabet,enppi).
club(magdy_atwa,enppi).
club(abdel_aziz_tawfik,enppi).
club(ghazali_mohammed,enppi).
club(ashour_al_taqui,enppi).
club(mohammed_ibrahim,enppi).
club(ahmed_abdul_zaher,enppi).
club(amr_zaki,enppi).
club(magdy_abdelaaty,enppi).
club(hossam_mabrouk,enppi).
club(abdelhamid_hassan,enppi).

club(haytham_hassan,masri).
club(ndubuisi_egbo,masri).
club(ndubuisi_egbo,imasri).
club(fawzy_samir,masri).
club(mohammed_mostafa_helwa,masri).
club(amr_al_safty,masri).
club(ibrahim_hassan,masri).
club(osama_ragab,masri).
club(mohammed_emara,masri).
club(samir_kamouna,masri).
club(karim_zekry,masri).
club(haytham_farouk,masri).
club(mohammed_salah,masri).
club(hani_saiid,masri).
club(mahmoud_eid,masri).
club(osama_al_sayed,masri).
club(abdallah_ragab,masri).
club(ahmed_hafez,masri).
club(mohammed_al_rayes,masri).
club(salah_amin,masri).
club(ahmed_farghali,masri).
club(mahmoud_saad,masri).
club(ashour_al_adham,masri).
club(amr_bassiouny,masri).
club(al_sayed_al_atbani,masri).
club(hossam_hassan,masri).
club(saliu_cobblah,masri).
club(saliu_cobblah,masri).
club(mohammed_zekri,masri).
club(mohammed_fadl,masri).
club(mohammed_al_genedy,masri).
club(geoffrey_massa,masri).
club(geoffrey_massa,masri).

club(shady_al_maamour,mekawleen).
club(mohammed_al_akabawy,mekawleen).
club(daouda_diakite,mekawleen).
club(youssef_abdelrahman,mekawleen).
club(mohammed_abdelsatar,mekawleen).
club(rami_hanafi,mekawleen).
club(mohammed_gamal,mekawleen).
club(mohammed_al_etrawy,mekawleen).
club(mohammed_ali,mekawleen).
club(ibrahim_al_bahnasi,mekawleen).
club(mohammed_al_ghanam,mekawleen).
club(khaled_nabil,mekawleen).
club(mohammed_ouda,mekawleen).
club(mohamed_al_hosari,mekawleen).
club(sherif_al_beyali,mekawleen).
club(mohammed_muselhy,mekawleen).
club(ahmed_mahmoud,mekawleen).
club(ayman_zein,mekawleen).
club(mahmoud_samir,mekawleen).
club(ehab_al_masri,mekawleen).
club(amir_salah,mekawleen).
club(mohammed_fahim,mekawleen).
club(tamer_adel,mekawleen).
club(talaat_moharam,mekawleen).

club(mohammed_fathi,ismaily).
club(mohammed_sobhi,ismaily).
club(amr_al_desouki,ismaily).
club(mahmoud_selim,ismaily).
club(moatasem_salem,ismaily).
club(sayed_moawad,ismaily).
club(ahmed_al_gamal,ismaily).
club(hesham_ali,ismaily).
club(sherif_abd_al_fadil,ismaily).
club(ahmed_saied,ismaily).
club(ayman_ramadan,ismaily).
club(ibrahim_yehia,ismaily).
club(ahmed_abdul_aziz,ismaily).
club(ahmed_khairy,ismaily).
club(samuel_johnson,ismaily).
club(ahmed_fathi,ismaily).
club(ali_gomaa,ismaily).
club(omar_gamal,ismaily).
club(abdallah_al_shahat,ismaily).
club(mohammed_soliman,ismaily).
club(hesham_ali,ismaily).
club(mohammed_mohsen,ismaily).
club(youssef_gamal,ismaily).
club(robert_akaruye,ismaily).
club(mohammed_salah_abou_greisha,ismaily).
club(jorge_celino,ismaily).
club(islam_shokri,ismaily).
club(mohammed_abdrabu,ismaily).
